import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from "sonner";
import { Header } from "@/components/layout/header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased`}
      >
        <Toaster position="top-center" richColors closeButton/>
        <Header />
        {children}
      </body>
    </html>
  );
}
